/*
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tdt4250.ganttproject.xtext.ui.internal.XtextActivator;

public class GpxUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("tdt4250.ganttproject.Gpx");
	}

}
