/*
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGpxScopeProvider extends DelegatingScopeProvider {
}
