/*
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.resource.DerivedStateAwareResource;
import org.eclipse.xtext.resource.DerivedStateAwareResourceDescriptionManager;
import org.eclipse.xtext.resource.IDerivedStateComputer;
import org.eclipse.xtext.resource.IResourceDescription;
import org.eclipse.xtext.resource.XtextResource;

import tdt4250.ganttproject.converter.GpxConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GpxRuntimeModule extends AbstractGpxRuntimeModule {
	
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return GpxConverterService.class;
	}
	
	public Class<? extends IDerivedStateComputer> bindIDerivedStateComputer() {
		    return GpxDerivedStateComputer.class;
	} 
	
	@Override
	public Class<? extends XtextResource> bindXtextResource() {
	    return DerivedStateAwareResource.class;
	}

	public Class<? extends IResourceDescription.Manager> bindIResourceDescriptionManager() {
	    return DerivedStateAwareResourceDescriptionManager.class;
	}
}
