/*
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject;

import org.eclipse.xtext.conversion.IValueConverterService;

import tdt4250.ganttproject.converter.GpxConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GpxRuntimeModule extends AbstractGpxRuntimeModule {
	
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return GpxConverterService.class;
	}
}
