/*
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GpxStandaloneSetup extends GpxStandaloneSetupGenerated {

	public static void doSetup() {
		new GpxStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
