/*
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GpxUiModule extends AbstractGpxUiModule {

	public GpxUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
