/**
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.gpx.impl;

import org.eclipse.emf.ecore.EClass;

import tdt4250.ganttproject.gpx.GpxPackage;
import tdt4250.ganttproject.gpx.Milestone;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Milestone</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MilestoneImpl extends AbstractTaskImpl implements Milestone {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MilestoneImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return GpxPackage.Literals.MILESTONE;
	}

} //MilestoneImpl
