/**
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.tests;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import tdt4250.ganttproject.GpxCustomGenerator;
import tdt4250.ganttproject.gpx.GpxPackage;
import tdt4250.ganttproject.gpx.Project;
import tdt4250.ganttproject.tests.GpxInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(GpxInjectorProvider.class)
@SuppressWarnings("all")
public class GpxTransformationTest {
  @Inject
  private ParseHelper<Project> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      GpxPackage.eINSTANCE.eClass();
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Project \'MyProject\'");
      _builder.newLine();
      _builder.newLine();
      _builder.append("Task \'Task 1\'{");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("Task \'Task 1.1\' lasts 5 days from 10.11.20;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("Task \'Task 1.2\' lasts 1 day, depends on \'Task 1.1\'");
      _builder.newLine();
      _builder.append("};");
      _builder.newLine();
      _builder.append("Task \'Task 2\' lasts 10 days, depends on \'Task 2\';");
      _builder.newLine();
      _builder.append("Milestone \'Phase 1\' planned 27.11.20, depends on \'Task 2\';");
      _builder.newLine();
      _builder.append("Task \'Task 3\' depends on \'Phase 1\'{");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("Task \'Task 3.1\' from 29.11.20 due 30.11.20;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("Task \'Task 3.2\' lasts 1 day;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("Task \'Task 3.3\' lasts 3 week, depends on \'Task 3.1\', \'Task 1\'");
      _builder.newLine();
      _builder.append("};");
      _builder.newLine();
      _builder.append("Task \'Task 4\' lasts 10 days, depends on \'Task 3.1\'");
      _builder.newLine();
      final Project result = this.parseHelper.parse(_builder);
      System.out.println(GpxCustomGenerator.generate(result));
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
