/*
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.generator;

import java.text.SimpleDateFormat
import java.util.Date
import tdt4250.ganttproject.gpx.DURATION_UNIT
import tdt4250.ganttproject.gpx.Milestone
import tdt4250.ganttproject.gpx.Project
import tdt4250.ganttproject.gpx.Task

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class GpxCustomGenerator {

	def static String generate(Project project) {
		generateXml(project, new StringBuilder).toString
	}
	
	def static CharSequence generateXml(Project project, StringBuilder stringBuilder) {
		stringBuilder << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" 
		generateProject(project, stringBuilder)
		return stringBuilder
	}
	
	
	def static operator_doubleLessThan(StringBuilder builder, String string) {
		return builder.append(string)
	}
	
	def static void generateProject(Project project, StringBuilder stringBuilder) {
		stringBuilder << 
		'''<project name="«project.name»" company="" webLink="http://" view-date="2021-01-01" view-index="0" gantt-divider-location="367" resource-divider-location="300" version="2.8.11" locale="en_US">''' <<
		"<description/>"
		generateCommonPreambule(stringBuilder)
		generateTasks(project, stringBuilder)
		generateCommonEnding(stringBuilder)
		stringBuilder << "
</project>"
	}
	
	def static void generateCommonPreambule(StringBuilder stringBuilder) {
		stringBuilder << 
		"<view zooming-state=\"default:8\" id=\"gantt-chart\">
   		    <field id=\"tpd3\" name=\"Name\" width=\"204\" order=\"0\"/>
			<field id=\"tpd4\" name=\"Begin date\" width=\"80\" order=\"1\"/>
			<field id=\"tpd5\" name=\"End date\" width=\"79\" order=\"2\"/>
        	<option id=\"color.recent\">
            	<![CDATA[#00cc66 #990066 #ffffcc #990099]]>
        	</option>
    	</view>
    	<view id=\"resource-table\">
        	<field id=\"0\" name=\"Name\" width=\"210\" order=\"0\"/>
	        <field id=\"1\" name=\"Default role\" width=\"86\" order=\"1\"/>
 	    </view>
        <calendars>
	        <day-types>
	            <day-type id=\"0\"/>
	            <day-type id=\"1\"/>
	            <default-week id=\"1\" name=\"default\" sun=\"1\" mon=\"0\" tue=\"0\" wed=\"0\" thu=\"0\" fri=\"0\" sat=\"1\"/>
	            <only-show-weekends value=\"false\"/>
	            <overriden-day-types/>
	            <days/>
	        </day-types>
	    </calendars>"
	}
	
	def static void generateTasks(Project project, StringBuilder stringBuilder) {
		stringBuilder <<
		"<tasks empty-milestones=\"true\">
        <taskproperties>
            <taskproperty id=\"tpd0\" name=\"type\" type=\"default\" valuetype=\"icon\"/>
            <taskproperty id=\"tpd1\" name=\"priority\" type=\"default\" valuetype=\"icon\"/>
            <taskproperty id=\"tpd2\" name=\"info\" type=\"default\" valuetype=\"icon\"/>
            <taskproperty id=\"tpd3\" name=\"name\" type=\"default\" valuetype=\"text\"/>
            <taskproperty id=\"tpd4\" name=\"begindate\" type=\"default\" valuetype=\"date\"/>
            <taskproperty id=\"tpd5\" name=\"enddate\" type=\"default\" valuetype=\"date\"/>
            <taskproperty id=\"tpd6\" name=\"duration\" type=\"default\" valuetype=\"int\"/>
            <taskproperty id=\"tpd7\" name=\"completion\" type=\"default\" valuetype=\"int\"/>
            <taskproperty id=\"tpd8\" name=\"coordinator\" type=\"default\" valuetype=\"text\"/>
            <taskproperty id=\"tpd9\" name=\"predecessorsr\" type=\"default\" valuetype=\"text\"/>
        </taskproperties>
"
		project.tasks.forEach[generateTask(it, stringBuilder)]
		stringBuilder <<
		"</tasks>"
	}
	
	def static dispatch void generateTask(Milestone task, StringBuilder stringBuilder) {
		stringBuilder <<'''
			<task id="«task.id»" name="«task.name»" color="#990066" meeting="true" start="«task.endDate != null? convertDate(task.endDate) : 0»" duration="0" complete="0" thirdDate="«task.endDate != null? convertDate(task.endDate) : 0»" thirdDate-constraint="0" expand="true">
		'''
//TODO list tasks which DEPEND on the current one /either bi-directional links in model or derived feature
        stringBuilder << "
			</task>"
	}
	def static dispatch void generateTask(Task task, StringBuilder stringBuilder) {
		stringBuilder << '''
			<task id="«task.id»" name="«task.name»" color="#990066" meeting="false" start="«task.endDate != null? convertDate(task.startDate) : 0»" duration="«adjustDurationToDays(task)»" complete="0" thirdDate="«task.endDate != null? convertDate(task.endDate) : 0»" thirdDate-constraint="0" expand="true">
		'''
//TODO list tasks which DEPEND on the current one /either bi-directional links in model or derived feature
        task.subtasks.forEach[generateTask(it, stringBuilder)]
        stringBuilder << "
			</task>"
	}
	
	def static int adjustDurationToDays(Task t) {
		return t.durationUnit == DURATION_UNIT.WEEK ? t.duration * 7 : t.duration	
	}
		
	def static void generateCommonEnding(StringBuilder stringBuilder) {
		stringBuilder <<
		"<resources/>
		<allocations/>
		<vacations/>
		<previous/>
		<roles roleset-name=\"Default\"/>"
	}

	def static StringBuilder operator_doubleLessThan(StringBuilder stringBuilder, Object o) {
		return stringBuilder.append(o);
	}
	
	def static convertDate(Date date) {
		val SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
		return dateFormat.format(date)
	}
}
