/**
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.gpx;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tdt4250.ganttproject.gpx.Dependency#getDependees <em>Dependees</em>}</li>
 *   <li>{@link tdt4250.ganttproject.gpx.Dependency#getDependant <em>Dependant</em>}</li>
 * </ul>
 *
 * @see tdt4250.ganttproject.gpx.GpxPackage#getDependency()
 * @model
 * @generated
 */
public interface Dependency extends EObject {
	/**
	 * Returns the value of the '<em><b>Dependees</b></em>' reference list.
	 * The list contents are of type {@link tdt4250.ganttproject.gpx.AbstractTask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Dependees</em>' reference list.
	 * @see tdt4250.ganttproject.gpx.GpxPackage#getDependency_Dependees()
	 * @model
	 * @generated
	 */
	EList<AbstractTask> getDependees();

	/**
	 * Returns the value of the '<em><b>Dependant</b></em>' container reference.
	 * It is bidirectional and its opposite is '{@link tdt4250.ganttproject.gpx.AbstractTask#getDependency <em>Dependency</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Dependant</em>' container reference.
	 * @see #setDependant(AbstractTask)
	 * @see tdt4250.ganttproject.gpx.GpxPackage#getDependency_Dependant()
	 * @see tdt4250.ganttproject.gpx.AbstractTask#getDependency
	 * @model opposite="dependency" transient="false"
	 * @generated
	 */
	AbstractTask getDependant();

	/**
	 * Sets the value of the '{@link tdt4250.ganttproject.gpx.Dependency#getDependant <em>Dependant</em>}' container reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Dependant</em>' container reference.
	 * @see #getDependant()
	 * @generated
	 */
	void setDependant(AbstractTask value);

} // Dependency
