/**
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.gpx;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Milestone</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tdt4250.ganttproject.gpx.GpxPackage#getMilestone()
 * @model
 * @generated
 */
public interface Milestone extends AbstractTask {
} // Milestone
