/**
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.gpx;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Project</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tdt4250.ganttproject.gpx.Project#getName <em>Name</em>}</li>
 *   <li>{@link tdt4250.ganttproject.gpx.Project#getTasks <em>Tasks</em>}</li>
 * </ul>
 *
 * @see tdt4250.ganttproject.gpx.GpxPackage#getProject()
 * @model
 * @generated
 */
public interface Project extends EObject {
	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see tdt4250.ganttproject.gpx.GpxPackage#getProject_Name()
	 * @model
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link tdt4250.ganttproject.gpx.Project#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
	 * The list contents are of type {@link tdt4250.ganttproject.gpx.AbstractTask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Tasks</em>' containment reference list.
	 * @see tdt4250.ganttproject.gpx.GpxPackage#getProject_Tasks()
	 * @model containment="true"
	 * @generated
	 */
	EList<AbstractTask> getTasks();

} // Project
