/**
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.gpx;

import java.util.Date;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tdt4250.ganttproject.gpx.Task#getDuration <em>Duration</em>}</li>
 *   <li>{@link tdt4250.ganttproject.gpx.Task#getDurationUnit <em>Duration Unit</em>}</li>
 *   <li>{@link tdt4250.ganttproject.gpx.Task#getStartDate <em>Start Date</em>}</li>
 * </ul>
 *
 * @see tdt4250.ganttproject.gpx.GpxPackage#getTask()
 * @model
 * @generated
 */
public interface Task extends AbstractTask {
	/**
	 * Returns the value of the '<em><b>Duration</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Duration</em>' attribute.
	 * @see #setDuration(int)
	 * @see tdt4250.ganttproject.gpx.GpxPackage#getTask_Duration()
	 * @model
	 * @generated
	 */
	int getDuration();

	/**
	 * Sets the value of the '{@link tdt4250.ganttproject.gpx.Task#getDuration <em>Duration</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Duration</em>' attribute.
	 * @see #getDuration()
	 * @generated
	 */
	void setDuration(int value);

	/**
	 * Returns the value of the '<em><b>Duration Unit</b></em>' attribute.
	 * The literals are from the enumeration {@link tdt4250.ganttproject.gpx.DURATION_UNIT}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Duration Unit</em>' attribute.
	 * @see tdt4250.ganttproject.gpx.DURATION_UNIT
	 * @see #setDurationUnit(DURATION_UNIT)
	 * @see tdt4250.ganttproject.gpx.GpxPackage#getTask_DurationUnit()
	 * @model
	 * @generated
	 */
	DURATION_UNIT getDurationUnit();

	/**
	 * Sets the value of the '{@link tdt4250.ganttproject.gpx.Task#getDurationUnit <em>Duration Unit</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Duration Unit</em>' attribute.
	 * @see tdt4250.ganttproject.gpx.DURATION_UNIT
	 * @see #getDurationUnit()
	 * @generated
	 */
	void setDurationUnit(DURATION_UNIT value);

	/**
	 * Returns the value of the '<em><b>Start Date</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Start Date</em>' attribute.
	 * @see #setStartDate(Date)
	 * @see tdt4250.ganttproject.gpx.GpxPackage#getTask_StartDate()
	 * @model
	 * @generated
	 */
	Date getStartDate();

	/**
	 * Sets the value of the '{@link tdt4250.ganttproject.gpx.Task#getStartDate <em>Start Date</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Start Date</em>' attribute.
	 * @see #getStartDate()
	 * @generated
	 */
	void setStartDate(Date value);

} // Task
