/*
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import tdt4250.ganttproject.services.GpxGrammarAccess;

@SuppressWarnings("all")
public class GpxSyntacticSequencer extends AbstractSyntacticSequencer {

	protected GpxGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Milestone_CommaKeyword_4_0_q;
	protected AbstractElementAlias match_Task_CommaKeyword_5_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (GpxGrammarAccess) access;
		match_Milestone_CommaKeyword_4_0_q = new TokenAlias(false, true, grammarAccess.getMilestoneAccess().getCommaKeyword_4_0());
		match_Task_CommaKeyword_5_0_q = new TokenAlias(false, true, grammarAccess.getTaskAccess().getCommaKeyword_5_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Milestone_CommaKeyword_4_0_q.equals(syntax))
				emit_Milestone_CommaKeyword_4_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Task_CommaKeyword_5_0_q.equals(syntax))
				emit_Task_CommaKeyword_5_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     endDate=Date (ambiguity) 'depends' 'on' dependency=Dependency
	 */
	protected void emit_Milestone_CommaKeyword_4_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     durationUnit=DURATION_UNIT (ambiguity) 'depends' 'on' dependency=Dependency
	 *     endDate=Date (ambiguity) 'depends' 'on' dependency=Dependency
	 *     name=STRING (ambiguity) 'depends' 'on' dependency=Dependency
	 *     startDate=Date (ambiguity) 'depends' 'on' dependency=Dependency
	 */
	protected void emit_Task_CommaKeyword_5_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
