/*
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import tdt4250.ganttproject.generator.GpxCustomGenerator
import tdt4250.ganttproject.gpx.GpxPackage
import tdt4250.ganttproject.gpx.Project

@ExtendWith(InjectionExtension)
@InjectWith(GpxInjectorProvider)
class GpxTransformationTest {
	@Inject
	ParseHelper<Project> parseHelper
	
	@Test
	def void loadModel() {
		GpxPackage.eINSTANCE.eClass
		val result = parseHelper.parse('''
Project 'MyProject'

Task 'Task 1'{
	Task 'Task 1.1' lasts 5 days from 10.11.20;
	Task 'Task 1.2' lasts 1 day, depends on 'Task 1.1'
};
Task 'Task 2' lasts 10 days, depends on 'Task 2';
Milestone 'Phase 1' planned 27.11.20, depends on 'Task 2';
Task 'Task 3' depends on 'Phase 1'{
	Task 'Task 3.1' from 29.11.20 due 30.11.20;
	Task 'Task 3.2' lasts 1 day;
	Task 'Task 3.3' lasts 3 week, depends on 'Task 3.1', 'Task 1'
};
Task 'Task 4' lasts 10 days, depends on 'Task 3.1'
		''')
		
		System.out.println(GpxCustomGenerator.generate(result))
		
	}
}
