/*
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GpxAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("tdt4250/ganttproject/parser/antlr/internal/InternalGpx.tokens");
	}
}
