/*
 * generated by Xtext 2.23.0
 */
package tdt4250.ganttproject.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tdt4250.ganttproject.parser.antlr.internal.InternalGpxParser;
import tdt4250.ganttproject.services.GpxGrammarAccess;

public class GpxParser extends AbstractAntlrParser {

	@Inject
	private GpxGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGpxParser createParser(XtextTokenStream stream) {
		return new InternalGpxParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Project";
	}

	public GpxGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GpxGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
